services:
  app:
    build:
      context: .
      target: dev-envs
    entrypoint:
    - sleep
    - infinity
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

