services:
  app:
    build:
      context: .
      target: dev-envs
    entrypoint:
    - sleep
    - infinity
    # image: docker/dev-environments-javascript:stable-1
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

